---
- name: Get windows disk facts
  community.windows.win_disk_facts:

- set_fact:
    disk: '{{ ansible_facts.disks|selectattr("system_disk")|first }}'
                                                                                                                        
- set_fact: 
    disk_available_gb: '{{ (disk.size/1024|pow(3))|round|int }}'

- name: Check storage size 5GB or above available space
  assert:
    that: disk_available_gb|int  > 5
