---
- name: Create directory structure
  ansible.windows.win_file:
    path: "{{ patch_path }}"
    state: directory

- name: update patch file path
  set_fact:
    update_file_path: '{{ patch_path }}\{{ patch_file }}'

- name: debug
  debug:
    msg: "{{ update_file_path }}"

- name: check update file
  win_stat:
    path: "{{ update_file_path }}"
  register: update_file
  when: (":" in update_file_path)

- include_tasks: check_disksize.yml

- name: debug file path
  debug:
    msg: "{{ update_file_path }}"

## temp copy patch file for testing ##
# - name: Copy sql patch file
#   ansible.windows.win_copy:
#     src: files/SQLServer2019-KB5030333-x64.exe
#     dest: "{{ patch_path }}"
#   when: (":" in update_file_path) and (not update_file.stat.exists)

# - name: download update file
#   win_get_url:
#     dest: "{{ update_file_path }}"
#     url: "{{ update_file_url }}"
#   register: download_update
#   until: download_update is success
#   delay: 3
#   retries: 5
#   when: (":" in update_file_path) and (not update_file.stat.exists)


- include_tasks: check_version.yml

- include_tasks: win_download.yml
  when: patch_build_version > sql_server_patchlevel

- name: patch check
  debug:
    msg: "Current patch level:  {{ sql_server_patchlevel }} / Target patch version: {{ patch_build_version }}"

- name: patch sql server version
  block:
    - name: Stop sqlserver and set service startup mode to manual
      ansible.windows.win_service:
        name: MSSQLSERVER
        start_mode: manual
        state: stopped

    - name: Reboot windows machine with 300 sec timeout
      ansible.windows.win_reboot:
        reboot_timeout: 300
    
    - name: patch SQL Server
      win_package:
        path: '{{ update_file_path }}'
        arguments:
          - /Q
          - /quiet
          - /IAcceptSQLServerLicenseTerms
          - /Action=Patch
          - /AllInstances
      register: sql_update

    - name: Start sqlserver and set service startup mode to auto
      ansible.windows.win_service:
        name: MSSQLSERVER
        start_mode: auto
        state: started
        
    - include_tasks: check_version.yml

    - name: remove sqlserver patch file
      ansible.windows.win_file:
        path: "{{ update_file_path }}"
        state: absent
  when: patch_build_version > sql_server_patchlevel

- name: patch status
  debug:
    msg: "No patch required."
  when: not (patch_build_version > sql_server_patchlevel)
