---
- name: Dowload file from blob container
  blob_download:
    storageAccountName: "{{ storageAccountName }}"
    storageAccountKey: "{{ storageAccountKey }}"
    containerName: "{{ containerName }}"
    blobName: "{{ patch_file }}"
    destinationPath: "{{ patch_path }}"

- name: Check if the file download success
  ansible.windows.win_stat:
    path: "{{ patch_path }}\\{{ patch_file }}"
  register: file_info